Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :users
  resources :invites
  resources :sensors
  resources :nodes
  #The website root
  root 'index#index'

  #This is for the invitation
  match '/signup/:invite_code' => 'users#new', :via => [:get], :as => 'redeem_invitation'
  match '/send_invitation/:id' => 'invites#send_invitation', :via => [:post], :as => 'send_invitation'

  #Readings routes
  resources :readings, only: [:index, :destroy, :show]
  #resources :invites, only: [:index, :show, :create]
  resources :graphs

  #api
   namespace :api do
     namespace :v1 do
       resources :readings, only: [:create]
     end
   end

if Clearance.configuration.routes_enabled?
  Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
    resources :passwords,
      controller: 'clearance/passwords',
      only: [:create, :new]

    resource :session,
      controller: 'clearance/sessions',
      only: [:create]

    resources :users,
      controller: 'clearance/users',
      only: Clearance.configuration.user_actions do
        resource :password,
          controller: 'clearance/passwords',
          #Added :show
          only: [:create, :edit, :update, :show]
      end

    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in_new'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out_new'

    if Clearance.configuration.allow_sign_up?
      get '/sign_up' => 'clearance/users#new', as: 'sign_up_new'
    end
  end
end


# **** DONT touch anything below unless you are sure you know what you're doing ****
# Autogenerated by clearance gem
#   resources :passwords, controller: "clearance/passwords", only: [:create, :new]
#   resource :session, controller: "clearance/sessions", only: [:create]

#   resources :users, controller: "clearance/users", only: [:create] do
#     resource :password,
#       controller: "clearance/passwords",
#       only: [:create, :edit, :update]
#   end
#   #These used to be as: "sign_in"
#   get "/sign_in" => "clearance/sessions#new", as: "sign_in_new"
#   delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out_new"
#   get "/sign_up" => "clearance/users#new", as: "sign_up_new"
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
