Rails.application.routes.draw do
  resources :sensors
  resources :nodes
  #The website root
  root 'index#index'

  #Readings routes
  resources :readings, only: [:index, :destroy, :show]

  resources :graphs

  #error log routes
  get '/logs' => 'index#logs'
 
  #for viewing the users
  #get '/users' => 'users#show'
  #get '/users' => 'users#destroy'
  #match 'Destroy' => 'users#destroy', via: :get 

  #api
   namespace :api do
     namespace :v1 do
       resources :readings, only: [:create]
     end
   end

# **** DONT touch anything below unless you are sure you know what you're doing ****
# Autogenerated by clearance gem
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  # need to use our users controller because we overwrote it
  #Mark - added show/destroy to be able to show all users
  resources :users, controller: "users", only: [:create, :show, :destroy, :index] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  #get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/sign_up" => "users#new", as: "sign_up"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
